# TEST UTILIZZO ARRAY #

In [2]:
import numpy as np #chiamo la libreria di numpy
testArray = np.array(['usa','canada','italia'])
testArray

array(['usa', 'canada', 'italia'], dtype='<U6')

In [6]:
y= np.array([[2,3,4],[4,5,6]])
y.shape # ti dice quante righe e colonne ci sono "(righe,colonne)"


(2, 3)

In [8]:
np.zeros((2,3)) #Crea matrici di "0" in base alle dimesioni che gli vengono date "(2,3)"

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.arange(1,10) #Crea un range sull'testArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1.,6.,6) #Crea un array con intermedi equidistanti (inizio intervallo,fine intervallo,distanza intervallo). "1." indica un float 

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [18]:
x = np.array([3,6,9,12])
x/3

array([1., 2., 3., 4.])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b                  # fa la somma del contenuto dell'array

array([5, 7, 9])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
